// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RideService.Data;

#nullable disable

namespace RideService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315124755_init_rides")]
    partial class init_rides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RideService.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision")
                        .HasColumnName("distance");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<string>("DropOffAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("drop_off_address");

                    b.Property<double>("DropOffLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("drop_off_latitude");

                    b.Property<double>("DropOffLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("drop_off_longitude");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_id");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_address");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_latitude");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("pickup_longitude");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_rides");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_rides_driver_id");

                    b.HasIndex("PassengerId")
                        .HasDatabaseName("ix_rides_passenger_id");

                    b.ToTable("rides", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
